#!/usr/bin/env bash
set -o errexit   # exit on error
set -o pipefail  # exit on error in pipes
set -o nounset   # exit on unset variable
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
cd "$ROOT_DIR"


# paths
INPUT_DIR="$ROOT_DIR/qtcreator"
OUTPUT_DIR="$ROOT_DIR/trace_history_gui/widgets"


# update function
function update() {
  NAME="$1"
  pyside2-uic "$INPUT_DIR/$NAME.ui" > "$OUTPUT_DIR/ui_$NAME.py"
}


# update ui

cd qtcreator

for file in *.ui; do

  # remove .ui extension to get name
  name="${file:0:-3}"

  # update
  update "$name"

done
